// <auto-generated />
namespace BookLover.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changedComments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedComments));
        
        string IMigrationMetadata.Id
        {
            get { return "202103111911572_changedComments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
